### ISSUE TITLE
Reorder simulations

### ISSUE THREAD

**Issue by Siel** [LAPKB/NPcore#17]
Because we are reordering the events prior to the simulation to guarantee they time vector is monotonic increasing after the lag is applied. The simulated observations might not be in the same order as the observed values. We have to keep track of the permutations that were made and reorder the simulations back.

This is important because the simulatied values are compared with the observed ones in the order of observations WITHOUT taking into consideration the lag.

When having multiple outeqs, this might cause big problems.

**Comment by mhovd** [comment]
I think we should abstract the observations for outeqs to e.g. a hashmap or similar, in order to connect each prediction to the relevant observation. I think we can do this by time (and outeq), as we won't really change the time of the observation.
Not sure how expensive that would be though.

**Comment by Siel** [comment]
That is my main concern, hashes are way slower than regular vectors. I suppose we can give it a try and benchmark results. Doing it that way would also require a big re-write of all the likelihood-calculation related code. Not sure about it.

Eeither way, the way is implemented right now is not complety correct and might end up with erroneous results if the circumstances are right.

**Comment by Siel** [comment]
Closed as it is not an issue right now. We might get into this later when cleaning up the code.
